### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by dinosaw** [skydrome/LazyMan#6]
Hello,

It's great to see some active (fork) development going on with this Kodi plugin, as I rely on it heavily.

I had a simple question regarding installation. What is the method you'd recommend for installing your v1.3.0? For actionbronson's version, there is a Kodi repository file (`addon.xml`) that makes it quick to install, however I don't think your version has this? Correct me if I'm wrong?

If you have no repository available, I assume just a manual install method is suggested? Which would consist of downloading the release file and dropping it in the `kodi/addons` directory? The thing that confused me about this is the fact that actionbronson's release was prefaced with `video` text (i.e. `video.lazyman.nhl.tv`) while yours is prefaced with `plugin` (i.e. `plugin.video.lazyman.nhl.tv`). Is that just a different depending on your version of Kodi or should it be renamed, or something else?

Lastly, which branch is the recommended version for installing? The `master` or the `kodi-19`?

Thanks again for picking development back up on this. It's greatly appreciated.

**Comment by skydrome** [comment]
Just realized I had a bunch of things not pushed to the repo before the season ended.
This will only work on kodi v19, remove previous version of the plugin and
grab the zip from https://github.com/skydrome/LazyMan/releases/tag/v1.3.0
install it like normal

**Comment by dinosaw** [comment]
> install it like normal

I believe you're referring to just choosing the option to install the add-on via a .zip file? Which is what I went ahead and did.

It looks like all dependencies and LazyMan installed successfully, however it fails to launch, mentioning to check the Kodi logs.

These were the error logs present when launching LazyMan:
https://pastebin.com/raw/AdfgXPEr

Any ideas what's going on?

Kodi Version: 19.0-ALPHA1 (18.9.701)

**Comment by skydrome** [comment]
folder where the settings are stored doesnt get created before the cache file tries to get written there. Grab an updated zip from https://github.com/skydrome/LazyMan/actions/runs/192627861

**Comment by dinosaw** [comment]
Apologies it took so long to report back to this ticket.

With the newly provided release, it appears to work without any issue at all. For reference:

- Fire TV Stick 4K
- Android 5.1.1
- Kodi 19.0-ALPHA1 (18.9.701)
- plugin.video.lazyman.nhl.tv-v1.3.0-11-ga835785.zip

Two things I'd like to mention as well:

1. Aside from making this compatible with Python 3, I love the little additions and fixes you have made here and there - the artwork being the best. Thanks for all of that.

2. This also fixed (intentionally or unintentionally) a problem I've had for as long as I've been using this Kodi add-on on my Fire Stick, and that was the fact that it only every played 720p60 streams and would never play any other streams. Your release allows me to bump that down to 540p (my downstairs TV isn't as close to the wi-fi) so I can enjoy a bufferless game.

The only other question I have at this time is, considering the developer behind LazyMan has called it quits, do you plan on continuing to support this add-on?

Thanks again!

**Comment by skydrome** [comment]
Yes, even without the game streams working, it can still be useful as somewhat of a tv-guide. And the highlights section i added for each team should always work.

**Comment by dinosaw** [comment]
Sounds good, thanks a lot! Closing.
